// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbZy-jEt-LzEQk6-hbUumhlcS2ZAmxThk',
    appId: '1:617791794288:web:8fcc2dfb00ef594b6898b5',
    messagingSenderId: '617791794288',
    projectId: 'food-collector-6a344',
    authDomain: 'food-collector-6a344.firebaseapp.com',
    storageBucket: 'food-collector-6a344.firebasestorage.app',
    measurementId: 'G-TW3JYYVZ91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVowFuMe7S1nlBLKtfIrFabSYcAsvlqM',
    appId: '1:617791794288:android:4fd530e2b01d70956898b5',
    messagingSenderId: '617791794288',
    projectId: 'food-collector-6a344',
    storageBucket: 'food-collector-6a344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPlwqSMt2mA6P9evpiBHZJff9zsXuam0',
    appId: '1:617791794288:ios:e67fc0ebeb787e756898b5',
    messagingSenderId: '617791794288',
    projectId: 'food-collector-6a344',
    storageBucket: 'food-collector-6a344.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEPlwqSMt2mA6P9evpiBHZJff9zsXuam0',
    appId: '1:617791794288:ios:e67fc0ebeb787e756898b5',
    messagingSenderId: '617791794288',
    projectId: 'food-collector-6a344',
    storageBucket: 'food-collector-6a344.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbZy-jEt-LzEQk6-hbUumhlcS2ZAmxThk',
    appId: '1:617791794288:web:eb10345cf9bacb6e6898b5',
    messagingSenderId: '617791794288',
    projectId: 'food-collector-6a344',
    authDomain: 'food-collector-6a344.firebaseapp.com',
    storageBucket: 'food-collector-6a344.firebasestorage.app',
    measurementId: 'G-YYR7CF8YRK',
  );
}
